const THEME_MEDIA = '(--nxt-theme-transition)'
interface ThemeRule {
  readonly rule: CSSMediaRule
  readonly condition: string
}
const cachedRules = new WeakMap<CSSStyleSheet, readonly ThemeRule[]>()
const activeRules = new Map<CSSMediaRule, string>()

/** Only host-generated CSS rules are enabled; this never traverses message DOM. */
export function enableThemeTransitions(): void {
  for (const sheet of document.styleSheets) {
    let rules = cachedRules.get(sheet)
    if (!rules) {
      try {
        rules = [...sheet.cssRules].flatMap((rule) =>
          rule instanceof CSSMediaRule && rule.conditionText.includes(THEME_MEDIA)
            ? [{ rule, condition: rule.conditionText }]
            : [],
        )
      } catch {
        // Cross-origin styles are not generated by the host and cannot be inspected.
        rules = []
      }
      cachedRules.set(sheet, rules)
    }
    for (const { rule, condition } of rules) {
      if (activeRules.has(rule)) continue
      // Minifiers may combine the sentinel with responsive/media conditions.
      // Replace only the sentinel, retaining every original condition.
      rule.media.mediaText = condition.replaceAll(THEME_MEDIA, '(min-width: 0px)')
      activeRules.set(rule, condition)
    }
  }
}

export function disableThemeTransitions(): void {
  for (const [rule, condition] of activeRules) rule.media.mediaText = condition
  activeRules.clear()
}
