declare const styles: {
  readonly accessLevelControl: string
  readonly accessLevelDescription: string
  readonly accessLevelExpand: string
  readonly accessLevelGranular: string
  readonly accessLevelGranularDisclosure: string
  readonly accessLevelHeading: string
  readonly accessLevelRange: string
  readonly accessLevelScale: string
  readonly accessLevelSlider: string
  readonly accessLevelStops: string
  readonly accessLevelTrack: string
  readonly activationCard: string
  readonly activationCopy: string
  readonly activationCount: string
  readonly activationDescription: string
  readonly activationGlyph: string
  readonly activationGrid: string
  readonly activationMeta: string
  readonly activationSection: string
  readonly agentActivity: string
  readonly agentAvatar: string
  readonly agentBlockers: string
  readonly agentCard: string
  readonly agentCardGrid: string
  readonly agentCardIdentity: string
  readonly agentCardMeta: string
  readonly agentCardTitle: string
  readonly agentCreatePage: string
  readonly agentDragOverlay: string
  readonly agentHeaderRow: string
  readonly agentNameLine: string
  readonly agentOverview: string
  readonly agentRow: string
  readonly appearanceSignature: string
  readonly appearanceSwatches: string
  readonly approvalNotice: string
  readonly attachment: string
  readonly authoringPhase: string
  readonly authoringPhases: string
  readonly avatar: string
  readonly bindingAgentActions: string
  readonly bindingAgentIdentity: string
  readonly bindingAgentRow: string
  readonly bindingEmpty: string
  readonly bindingEmptyIcon: string
  readonly bindingEventSettings: string
  readonly bindingInspector: string
  readonly bindingNextStep: string
  readonly bindingSettings: string
  readonly bindingSourceRow: string
  readonly boundChannelList: string
  readonly boundChannelName: string
  readonly boundChannelRow: string
  readonly cacheComposition: string
  readonly cacheCompositionTrack: string
  readonly cacheCoverage: string
  readonly cacheHeader: string
  readonly cacheLatest: string
  readonly cacheMetrics: string
  readonly cacheSegmentMiss: string
  readonly cacheSegmentRead: string
  readonly cacheSegmentWrite: string
  readonly cacheTotals: string
  readonly cacheTrend: string
  readonly cacheTrendBar: string
  readonly cacheTrendBarActive: string
  readonly cacheTrendBarUnknown: string
  readonly cacheTrendPlot: string
  readonly cacheUsageCard: string
  readonly canvasStage: string
  readonly canvasStageInner: string
  readonly canvasTab: string
  readonly capabilityChoices: string
  readonly capabilitySubsection: string
  readonly capabilitySubsectionHeader: string
  readonly channelDangerRow: string
  readonly channelDetailRow: string
  readonly channelDetails: string
  readonly channelDirectory: string
  readonly channelGroup: string
  readonly channelGroupHeader: string
  readonly channelGroupHeaderActive: string
  readonly channelGroups: string
  readonly channelLink: string
  readonly channelLinkActive: string
  readonly channelRename: string
  readonly channelRow: string
  readonly channelSessionInspector: string
  readonly collapsedInspectorDock: string
  readonly compactList: string
  readonly composer: string
  readonly composerInfo: string
  readonly composerInput: string
  readonly composerMode: string
  readonly composerModeRow: string
  readonly composerModeSpacer: string
  readonly composerSend: string
  readonly composerWebAction: string
  readonly connectionActivityBody: string
  readonly connectionActivityList: string
  readonly connectionAliasEditor: string
  readonly connectionNavItem: string
  readonly connectionNavItemActive: string
  readonly connectionNavList: string
  readonly connectionProgress: string
  readonly connectionWorkspace: string
  readonly contentLine: string
  readonly contextCharts: string
  readonly contextFigure: string
  readonly contextRing: string
  readonly contextSector: string
  readonly contextSectorActive: string
  readonly contextTooltip: string
  readonly contextUsageCard: string
  readonly conversationEmpty: string
  readonly conversationHeader: string
  readonly conversationHeaderActions: string
  readonly conversationInspectorDock: string
  readonly conversationMain: string
  readonly conversationPage: string
  readonly conversationTitleRow: string
  readonly createSummary: string
  readonly creatorCanvas: string
  readonly creatorEvidence: string
  readonly creatorGuide: string
  readonly creatorIntro: string
  readonly creatorLaunchPanel: string
  readonly creatorPage: string
  readonly creatorSaveActions: string
  readonly creatorSaveGrid: string
  readonly creatorSavePanel: string
  readonly creatorStartGrid: string
  readonly creatorStartPanel: string
  readonly creatorTaskSummary: string
  readonly creatorWorkspace: string
  readonly creatorWorkspaceTask: string
  readonly dangerSection: string
  readonly dark: string
  readonly desktopContentStage: string
  readonly desktopPage: string
  readonly detailPage: string
  readonly dialogChoice: string
  readonly dragOverlay: string
  readonly dropTarget: string
  readonly dynamicSlotSurface: string
  readonly emptyState: string
  readonly eventInner: string
  readonly extensionActionPanel: string
  readonly extensionDangerZone: string
  readonly extensionDetailGrid: string
  readonly extensionDropZone: string
  readonly extensionEmptyActions: string
  readonly extensionExportPanel: string
  readonly extensionFileButton: string
  readonly extensionFileInput: string
  readonly extensionHeader: string
  readonly extensionImportReview: string
  readonly extensionMetaLine: string
  readonly extensionNavItem: string
  readonly extensionNavItemActive: string
  readonly extensionNavList: string
  readonly extensionOverview: string
  readonly extensionPrimarySection: string
  readonly extensionRevisionPicker: string
  readonly extensionRow: string
  readonly extensionSummary: string
  readonly extensionSummaryCopy: string
  readonly extensionTransferGrid: string
  readonly extensionTransferSection: string
  readonly extensionWorkspace: string
  readonly extensionsPage: string
  readonly facts: string
  readonly formLayout: string
  readonly formStack: string
  readonly headerActionLabel: string
  readonly historyNotice: string
  readonly hostUiPageCopy: string
  readonly hostUiPageDrag: string
  readonly hostUiPageManager: string
  readonly hostUiPageRow: string
  readonly identityCell: string
  readonly inlineApproval: string
  readonly inlineFieldAction: string
  readonly inlineFieldHint: string
  readonly inspector: string
  readonly inspectorChrome: string
  readonly inspectorChromeBody: string
  readonly inspectorChromeHeader: string
  readonly inspectorExpanded: string
  readonly inspectorFacts: string
  readonly inspectorPane: string
  readonly inspectorPanel: string
  readonly inspectorRegion: string
  readonly inspectorRegionBody: string
  readonly inspectorSectionHead: string
  readonly inspectorSplitter: string
  readonly inspectorToggle: string
  readonly jumpBottom: string
  readonly kindMessage: string
  readonly kindTag: string
  readonly kindTool: string
  readonly linkRow: string
  readonly listHeader: string
  readonly markdownPart: string
  readonly masterButton: string
  readonly masterButtonActive: string
  readonly masterCopy: string
  readonly masterDetail: string
  readonly masterList: string
  readonly message: string
  readonly messageAvatar: string
  readonly messageBody: string
  readonly messageContent: string
  readonly messageHeader: string
  readonly messageImage: string
  readonly messageImageLink: string
  readonly messageList: string
  readonly messageListInner: string
  readonly messageMention: string
  readonly messageQuote: string
  readonly messageUnsupported: string
  readonly moreCapabilities: string
  readonly navCopy: string
  readonly notificationActions: string
  readonly optionalTests: string
  readonly overviewBlocker: string
  readonly overviewFacts: string
  readonly overviewSummary: string
  readonly page: string
  readonly performanceCard: string
  readonly performanceCoverage: string
  readonly performanceHeader: string
  readonly performanceMetrics: string
  readonly performancePrimary: string
  readonly performanceTotals: string
  readonly performanceTrend: string
  readonly performanceTrendBar: string
  readonly performanceTrendBarActive: string
  readonly performanceTrendBarUnknown: string
  readonly performanceTrendPlot: string
  readonly plot: string
  readonly plotLabels: string
  readonly plotSeg: string
  readonly plotSegInternal: string
  readonly plotSegSelected: string
  readonly plotSegSend: string
  readonly plotSegTool: string
  readonly plotTrack: string
  readonly plotTurn: string
  readonly qrLoginCode: string
  readonly qrLoginPanel: string
  readonly railEmpty: string
  readonly revisionNotice: string
  readonly riskLabel: string
  readonly rowActions: string
  readonly runtimeCard: string
  readonly runtimeDataSurface: string
  readonly runtimeEmpty: string
  readonly runtimeEmptyIcon: string
  readonly runtimeTail: string
  readonly secondaryText: string
  readonly section: string
  readonly sectionActionRow: string
  readonly sectionBar: string
  readonly sectionDivider: string
  readonly sectionHeading: string
  readonly selRail: string
  readonly settingsGroup: string
  readonly settingsNav: string
  readonly settingsNavItem: string
  readonly settingsNavItemActive: string
  readonly settingsPage: string
  readonly settingsSection: string
  readonly sortableOrigin: string
  readonly srOnly: string
  readonly staticRow: string
  readonly switchList: string
  readonly sysLine: string
  readonly systemAdapterCard: string
  readonly systemAdapterGrid: string
  readonly systemAdapterIntro: string
  readonly systemEvent: string
  readonly systemEventIcon: string
  readonly systemEventMain: string
  readonly systemEventRule: string
  readonly tagList: string
  readonly testRow: string
  readonly testRows: string
  readonly thinkBody: string
  readonly toolArgs: string
  readonly toolArrow: string
  readonly toolCard: string
  readonly toolLine: string
  readonly toolName: string
  readonly toolOut: string
  readonly toolRow: string
  readonly toolRowGroup: string
  readonly toolRowTrigger: string
  readonly traj: string
  readonly trajBar: string
  readonly trajBarCopy: string
  readonly trajContent: string
  readonly trajDetailHead: string
  readonly trajEmpty: string
  readonly trajEvent: string
  readonly trajEventCell: string
  readonly trajSearch: string
  readonly trajTable: string
  readonly trajTableWrap: string
  readonly trajTime: string
  readonly trajTimeCell: string
  readonly trajectoryHeader: string
  readonly trajectoryIdleRow: string
  readonly trajectoryStepMark: string
  readonly trajectorySteps: string
  readonly trajectorySummary: string
  readonly trajectoryTools: string
  readonly treeActivityIndicator: string
  readonly treeApprovalIndicator: string
  readonly treeCopy: string
  readonly treeRowDragHandle: string
  readonly treeStateIndicator: string
  readonly truncate: string
  readonly turnChip: string
  readonly turnRail: string
  readonly unread: string
  readonly userAvatar: string
  readonly userChannels: string
  readonly userConnection: string
  readonly userGroup: string
  readonly userGroups: string
  readonly userIdentity: string
  readonly userLoadMore: string
  readonly userNotices: string
  readonly userPagination: string
  readonly userRow: string
  readonly userRows: string
  readonly userTable: string
  readonly userTableBody: string
  readonly userTableHeader: string
  readonly userToolbar: string
  readonly userToolbarActions: string
  readonly userToolbarFields: string
  readonly userWorkspace: string
  readonly usersPage: string
  readonly viewSwitch: string
  readonly webSearchSetup: string
  readonly workDot: string
  readonly workDotFail: string
  readonly workDotOk: string
  readonly workDotRun: string
  readonly workRow: string
  readonly workStream: string
  readonly workStreamChevron: string
  readonly workStreamDetails: string
  readonly workStreamSummary: string
  readonly workSummaryRow: string
  readonly workToolCount: string
  readonly workbenchDoc: string
  readonly workbenchInspector: string
  readonly workbenchPage: string
  readonly workbenchSection: string
  readonly workbenchStatus: string
  readonly workspaceLead: string
}

export default styles
